[package]
name = "whyyoutypesofastagean"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.7.0"
winit = "0.25.0"
async-std = { version = "1.9", features = ["attributes"] }
